import type { EndClient } from "@/lib/types"

export const MOCK_END_CLIENTS: EndClient[] = [
  {
    id: "client-1",
    businessId: "biz-padel-norte",
    fullName: "Martín Aguirre",
    phone: "+54 9 11 5123-4001",
    email: "martin.aguirre@gmail.com",
    loyaltyPoints: 320,
    preferredChannel: "whatsapp",
  },
  {
    id: "client-2",
    businessId: "biz-padel-norte",
    fullName: "Lucía Fernández",
    phone: "+54 9 11 5123-4002",
    email: "lucia.fdez@gmail.com",
    loyaltyPoints: 150,
    preferredChannel: "whatsapp",
  },
  {
    id: "client-3",
    businessId: "biz-padel-norte",
    fullName: "Diego Sosa",
    phone: "+54 9 11 5123-4003",
    loyaltyPoints: 80,
    preferredChannel: "phone",
  },
  {
    id: "client-4",
    businessId: "biz-padel-norte",
    fullName: "Carolina Méndez",
    phone: "+54 9 11 5123-4004",
    email: "caro.mendez@outlook.com",
    loyaltyPoints: 540,
    preferredChannel: "web",
  },
  {
    id: "client-5",
    businessId: "biz-padel-norte",
    fullName: "Pablo Giménez",
    phone: "+54 9 11 5123-4005",
    loyaltyPoints: 0,
    preferredChannel: "whatsapp",
  },
  {
    id: "client-6",
    businessId: "biz-padel-norte",
    fullName: "Sofía Ramírez",
    phone: "+54 9 11 5123-4006",
    email: "sofia.ramirez@gmail.com",
    loyaltyPoints: 210,
    preferredChannel: "whatsapp",
  },
  {
    id: "client-7",
    businessId: "biz-padel-norte",
    fullName: "Federico Luna",
    phone: "+54 9 11 5123-4007",
    loyaltyPoints: 95,
    preferredChannel: "phone",
  },
  {
    id: "client-8",
    businessId: "biz-padel-norte",
    fullName: "Valentina Ortiz",
    phone: "+54 9 11 5123-4008",
    email: "vale.ortiz@gmail.com",
    loyaltyPoints: 400,
    preferredChannel: "whatsapp",
  },
]
