/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BackofficeRouteImport } from './routes/backoffice'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditoriaRouteImport } from './routes/admin.auditoria'
import { Route as AdminNegociosRouteImport } from './routes/admin.negocios'
import { Route as AdminPlanesRouteImport } from './routes/admin.planes'
import { Route as BackofficeIndexRouteImport } from './routes/backoffice.index'
import { Route as BackofficeAgendaRouteImport } from './routes/backoffice.agenda'
import { Route as BackofficeAjustesRouteImport } from './routes/backoffice.ajustes'
import { Route as BackofficeClientesRouteImport } from './routes/backoffice.clientes'
import { Route as BackofficeEquipoRouteImport } from './routes/backoffice.equipo'
import { Route as BackofficeNotificacionesRouteImport } from './routes/backoffice.notificaciones'
import { Route as BackofficePlanRouteImport } from './routes/backoffice.plan'
import { Route as BackofficeReportesRouteImport } from './routes/backoffice.reportes'
import { Route as BackofficeServiciosRouteImport } from './routes/backoffice.servicios'
import { Route as SitioSlugRouteImport } from './routes/sitio.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeRoute = BackofficeRouteImport.update({
  id: '/backoffice',
  path: '/backoffice',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNegociosRoute = AdminNegociosRouteImport.update({
  id: '/negocios',
  path: '/negocios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanesRoute = AdminPlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => AdminRoute,
} as any)
const BackofficeIndexRoute = BackofficeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeAgendaRoute = BackofficeAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeAjustesRoute = BackofficeAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeClientesRoute = BackofficeClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeEquipoRoute = BackofficeEquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeNotificacionesRoute =
  BackofficeNotificacionesRouteImport.update({
    id: '/notificaciones',
    path: '/notificaciones',
    getParentRoute: () => BackofficeRoute,
  } as any)
const BackofficePlanRoute = BackofficePlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeReportesRoute = BackofficeReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeServiciosRoute = BackofficeServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => BackofficeRoute,
} as any)
const SitioSlugRoute = SitioSlugRouteImport.update({
  id: '/sitio/$slug',
  path: '/sitio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/backoffice': typeof BackofficeRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/negocios': typeof AdminNegociosRoute
  '/admin/planes': typeof AdminPlanesRoute
  '/backoffice/agenda': typeof BackofficeAgendaRoute
  '/backoffice/ajustes': typeof BackofficeAjustesRoute
  '/backoffice/clientes': typeof BackofficeClientesRoute
  '/backoffice/equipo': typeof BackofficeEquipoRoute
  '/backoffice/notificaciones': typeof BackofficeNotificacionesRoute
  '/backoffice/plan': typeof BackofficePlanRoute
  '/backoffice/reportes': typeof BackofficeReportesRoute
  '/backoffice/servicios': typeof BackofficeServiciosRoute
  '/sitio/$slug': typeof SitioSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/backoffice/': typeof BackofficeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/negocios': typeof AdminNegociosRoute
  '/admin/planes': typeof AdminPlanesRoute
  '/backoffice/agenda': typeof BackofficeAgendaRoute
  '/backoffice/ajustes': typeof BackofficeAjustesRoute
  '/backoffice/clientes': typeof BackofficeClientesRoute
  '/backoffice/equipo': typeof BackofficeEquipoRoute
  '/backoffice/notificaciones': typeof BackofficeNotificacionesRoute
  '/backoffice/plan': typeof BackofficePlanRoute
  '/backoffice/reportes': typeof BackofficeReportesRoute
  '/backoffice/servicios': typeof BackofficeServiciosRoute
  '/sitio/$slug': typeof SitioSlugRoute
  '/admin': typeof AdminIndexRoute
  '/backoffice': typeof BackofficeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/backoffice': typeof BackofficeRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/negocios': typeof AdminNegociosRoute
  '/admin/planes': typeof AdminPlanesRoute
  '/backoffice/agenda': typeof BackofficeAgendaRoute
  '/backoffice/ajustes': typeof BackofficeAjustesRoute
  '/backoffice/clientes': typeof BackofficeClientesRoute
  '/backoffice/equipo': typeof BackofficeEquipoRoute
  '/backoffice/notificaciones': typeof BackofficeNotificacionesRoute
  '/backoffice/plan': typeof BackofficePlanRoute
  '/backoffice/reportes': typeof BackofficeReportesRoute
  '/backoffice/servicios': typeof BackofficeServiciosRoute
  '/sitio/$slug': typeof SitioSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/backoffice/': typeof BackofficeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/backoffice'
    | '/login'
    | '/admin/auditoria'
    | '/admin/negocios'
    | '/admin/planes'
    | '/backoffice/agenda'
    | '/backoffice/ajustes'
    | '/backoffice/clientes'
    | '/backoffice/equipo'
    | '/backoffice/notificaciones'
    | '/backoffice/plan'
    | '/backoffice/reportes'
    | '/backoffice/servicios'
    | '/sitio/$slug'
    | '/admin/'
    | '/backoffice/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/auditoria'
    | '/admin/negocios'
    | '/admin/planes'
    | '/backoffice/agenda'
    | '/backoffice/ajustes'
    | '/backoffice/clientes'
    | '/backoffice/equipo'
    | '/backoffice/notificaciones'
    | '/backoffice/plan'
    | '/backoffice/reportes'
    | '/backoffice/servicios'
    | '/sitio/$slug'
    | '/admin'
    | '/backoffice'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/backoffice'
    | '/login'
    | '/admin/auditoria'
    | '/admin/negocios'
    | '/admin/planes'
    | '/backoffice/agenda'
    | '/backoffice/ajustes'
    | '/backoffice/clientes'
    | '/backoffice/equipo'
    | '/backoffice/notificaciones'
    | '/backoffice/plan'
    | '/backoffice/reportes'
    | '/backoffice/servicios'
    | '/sitio/$slug'
    | '/admin/'
    | '/backoffice/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BackofficeRoute: typeof BackofficeRouteWithChildren
  LoginRoute: typeof LoginRoute
  SitioSlugRoute: typeof SitioSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice': {
      id: '/backoffice'
      path: '/backoffice'
      fullPath: '/backoffice'
      preLoaderRoute: typeof BackofficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/negocios': {
      id: '/admin/negocios'
      path: '/negocios'
      fullPath: '/admin/negocios'
      preLoaderRoute: typeof AdminNegociosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/planes': {
      id: '/admin/planes'
      path: '/planes'
      fullPath: '/admin/planes'
      preLoaderRoute: typeof AdminPlanesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/backoffice/': {
      id: '/backoffice/'
      path: '/'
      fullPath: '/backoffice/'
      preLoaderRoute: typeof BackofficeIndexRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/agenda': {
      id: '/backoffice/agenda'
      path: '/agenda'
      fullPath: '/backoffice/agenda'
      preLoaderRoute: typeof BackofficeAgendaRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/ajustes': {
      id: '/backoffice/ajustes'
      path: '/ajustes'
      fullPath: '/backoffice/ajustes'
      preLoaderRoute: typeof BackofficeAjustesRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/clientes': {
      id: '/backoffice/clientes'
      path: '/clientes'
      fullPath: '/backoffice/clientes'
      preLoaderRoute: typeof BackofficeClientesRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/equipo': {
      id: '/backoffice/equipo'
      path: '/equipo'
      fullPath: '/backoffice/equipo'
      preLoaderRoute: typeof BackofficeEquipoRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/notificaciones': {
      id: '/backoffice/notificaciones'
      path: '/notificaciones'
      fullPath: '/backoffice/notificaciones'
      preLoaderRoute: typeof BackofficeNotificacionesRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/plan': {
      id: '/backoffice/plan'
      path: '/plan'
      fullPath: '/backoffice/plan'
      preLoaderRoute: typeof BackofficePlanRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/reportes': {
      id: '/backoffice/reportes'
      path: '/reportes'
      fullPath: '/backoffice/reportes'
      preLoaderRoute: typeof BackofficeReportesRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/servicios': {
      id: '/backoffice/servicios'
      path: '/servicios'
      fullPath: '/backoffice/servicios'
      preLoaderRoute: typeof BackofficeServiciosRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/sitio/$slug': {
      id: '/sitio/$slug'
      path: '/sitio/$slug'
      fullPath: '/sitio/$slug'
      preLoaderRoute: typeof SitioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminNegociosRoute: typeof AdminNegociosRoute
  AdminPlanesRoute: typeof AdminPlanesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminNegociosRoute: AdminNegociosRoute,
  AdminPlanesRoute: AdminPlanesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BackofficeRouteChildren {
  BackofficeAgendaRoute: typeof BackofficeAgendaRoute
  BackofficeAjustesRoute: typeof BackofficeAjustesRoute
  BackofficeClientesRoute: typeof BackofficeClientesRoute
  BackofficeEquipoRoute: typeof BackofficeEquipoRoute
  BackofficeNotificacionesRoute: typeof BackofficeNotificacionesRoute
  BackofficePlanRoute: typeof BackofficePlanRoute
  BackofficeReportesRoute: typeof BackofficeReportesRoute
  BackofficeServiciosRoute: typeof BackofficeServiciosRoute
  BackofficeIndexRoute: typeof BackofficeIndexRoute
}

const BackofficeRouteChildren: BackofficeRouteChildren = {
  BackofficeAgendaRoute: BackofficeAgendaRoute,
  BackofficeAjustesRoute: BackofficeAjustesRoute,
  BackofficeClientesRoute: BackofficeClientesRoute,
  BackofficeEquipoRoute: BackofficeEquipoRoute,
  BackofficeNotificacionesRoute: BackofficeNotificacionesRoute,
  BackofficePlanRoute: BackofficePlanRoute,
  BackofficeReportesRoute: BackofficeReportesRoute,
  BackofficeServiciosRoute: BackofficeServiciosRoute,
  BackofficeIndexRoute: BackofficeIndexRoute,
}

const BackofficeRouteWithChildren = BackofficeRoute._addFileChildren(
  BackofficeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BackofficeRoute: BackofficeRouteWithChildren,
  LoginRoute: LoginRoute,
  SitioSlugRoute: SitioSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
